# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- name: JFROG_CLI_BUILD_NAME
  value: dotnet-lib
- name: JFROG_CLI_BUILD_NUMBER
  value: $(Build.BuildNumber)
- name: JFROG_CLI_LOG_LEVEL
  value: DEBUG 
- name: JFROG_CLI_TEMP_DIR
  value: /home/vsts/work/_temp

pool:
  vmImage: ubuntu-latest

jobs:
- job: dotnet_lib
  steps:  
  - task: JfrogCliV2@1
    inputs:
      jfrogPlatformConnection: 'yann-sbx'
      command: |
        jf -v
        date
        echo ${JFROG_CLI_BUILD_NUMBER}
        jf nuget config --repo-resolve ps-nuget

  - task: CmdLine@2
    inputs:
      script: |
        env | grep JFROG 
        ls -l ${AGENT_TEMPDIRECTORY}
        ls -l ${JFROG_CLI_TEMP_DIR}
        ls -l ${SYSTEM_DEFAULTWORKINGDIRECTORY}
        pwd
        ls -l 
    displayName: workaround for JFrog Audit


