# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- azure-pipelines

pool:
  vmImage: ubuntu-latest

jobs:
- job: dotnet_lib
  steps:  
  - task: CmdLine@2
    inputs:
      script: |
        ls -l
        cd MyLib/
        ls -l
  - task: JFrogAudit@1
    inputs:
      xrayConnection: 'new-stg-soleng-xray'
      watchesSource: 'none'
      allowFailBuild: false
      workingDirectory: MyLib/greeting/
  - task: CmdLine@2
    inputs:
      script: |
        ls -l
  - task: JFrogDotnetCore@1
    inputs:
      command: 'restore'
      artifactoryConnection: 'new-stg-soleng'
      targetResolveRepo: 'urs-dotnet'
      rootPath: 'MyLib/*.sln'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
  - task: DotNetCoreCLI@2
    inputs:
      command: 'build'
      projects: 'MyLib'
      arguments: '-c Release'
  - task: JFrogDotnetCore@1
    inputs:
      command: 'push'
      artifactoryConnection: 'new-stg-soleng'
      targetDeployRepo: 'urs-dotnet'
      targetDeployPath: 'azure'
      pathToNupkg: 'MyLib/greeting/**/*.nupkg'
      collectBuildInfo: true
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'
      includeEnvVars: true
  - task: JFrogPublishBuildInfo@1
    inputs:
      artifactoryConnection: 'new-stg-soleng'
      buildName: '$(Build.DefinitionName)'
      buildNumber: '$(Build.BuildNumber)'